### ISSUE TITLE
Geolocation wrong

### ISSUE THREAD

**Issue by nesciens** [davidgfnet/whatsapp-purple#208]
Functions str2dbl and dbl2str both are incorrect for circa 55% of inputs, namely for all non-integral negative inputs and non-integral inputs whose first decimal is 0. In particular, location messages are inaccurate in the western and southern hemispheres and near integral latitudes and longitudes.

Moreover the use of dbl2str in query_chat_location leaks memory.

For my patch writing, how do you feel about using glib [1] or istringstreams [2] in whatsapp_purple.cc?

[1] https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-strtod
[2] https://stackoverflow.com/questions/1333451/c-locale-independent-atof

**Comment by davidgfnet** [comment]
Ops you're right, hehe. I should kick myself for such a basic error. Thanks again.
BTW feel free to submit pull requests any time you want!

**Comment by nesciens** [comment]
This happens to all of us :).

To not shoot myself in the foot too, I'd like to delegate the parsing needed for str2dbl to a library. So, are you okay with using istringstream or glib in the C++-code of whatsapp_purple.cc?

**Comment by davidgfnet** [comment]
Actually... how do you use the library without all the locale-dependant stuff?

**Comment by nesciens** [comment]
dbl2str remains wrong for negative numbers, as modf gives the fractional part with the same sign as the original float. Since this is in a c-file where you're using glib, I'd just use g_ascii_dtostr [1]. (It would seem tempting to just replace b by abs(b), but this becomes problematic when a is 0, as that can be +0 or -0... so you'd have to get the sign separately from the original float. Not nice.)

str2dbl remains wrong for input where the fractional part starts with 0, effectively turning 3.05 into 3.5.
For str2dbl I'd use g_ascii_strtod, or the istringstream magic from [2].

[1] https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-dtostr
[2] https://stackoverflow.com/questions/1333451/c-locale-independent-atof

**Comment by nesciens** [comment]
Actually, g_ascii_formatd might be better than g_ascii_dtostr, to make sure exponents don't appear around latitude/longitude 0. Let me check the printf docs on the right format.

**Comment by nesciens** [comment]
This should do the trick for dbl2str:
#include <glib.h>
#include <glib/gprintf.h>
char buf[1+3+1+8+1] = ""; /* sign, 3 digits, period, 8 decimals, \0-termination */
g_ascii_formatd(buf, sizeof buf, "%.8f", val);

**Comment by davidgfnet** [comment]
Does this guarantee a "dot" in the number (I don't want any commas).
And BTW how can we handle str2dbl in a portable and locale-agnostic way? My patch should fix that but it's ugly :)

**Comment by nesciens** [comment]
Yes, it will use a dot; that is the point of the `_ascii_`-part. The glib reference at [1] explicitly says "Converts a gdouble to a string, using the '.' as decimal point.".

The following, which is copied from [2], converts the string `pField` to double `longitude` in a locale-agnostic way, where "locale-agnostic" means "using the C-locale and without setting the global locale":

    #include <sstream>
    #include <locale>
    float longitude = 0.0f;
    std::istringstream istr(pField);
    istr.imbue(std::locale("C"));
    istr >> longitude;

[1] https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-formatd
[2] https://stackoverflow.com/questions/1333451/c-locale-independent-atof

**Comment by nesciens** [comment]
The point of using glib/stringstream instead of stdio/stdlib, is that the former offer functions to locally and thread-safely use the C-locale, while the latter do not. Reading back, I completely failed to make this clear. Sorry about that.

**Comment by davidgfnet** [comment]
Oh I see, the sampe code is much of a clarification.
Thanks I'll redo that when I got some time.

**Comment by nesciens** [comment]
Well... dbl2str is still broken for negative inputs.

For instance, it turns -1.23456789 into -1.-23456789. From `man modf` (emphasis mine): "The `modf()` function breaks the argument `x` into an integral part and a fractional part, each of which **has the same sign as `x`.**"

I suggest
```
#include <glib.h>
#include <glib/gprintf.h>
char buf[1+3+1+8+1] = ""; /* sign, 3 digits, period, 8 decimals, \0-termination */
g_ascii_formatd(buf, sizeof buf, "%.8f", val);
```
